import PageTitle from "../Helpers/PageTitle";
import Layout from "../Partials/Layout";

export default function TermsCondition() {
  return (
    <Layout childrenClasses="pt-0 pb-0">
      <div className="terms-condition-page w-full bg-white pb-[50px]">
        <div className="w-full mb-[50px]">
          <PageTitle
            breadcrumb={[
              { name: "home", path: "/" },
              { name: "Terms and condition", path: "/terms-conditions" },
            ]}
            title="Terms and Condition"
          />
        </div>
        <div className="w-full">
          <div className="container-x mx-auto">
            <div className="content-item w-full">
              <h2 className="text-[18px] font-medium text-qblack mb-5">
                OVERVIEW
              </h2>
              <p className="text-[15px] text-qgraytwo leading-7">
               This website (https://thebearhouse.com/), hereafter referred to as the “Site” or “Website,” is operated by The Bear House, with its registered office at 123 Commerce Street, Bengaluru, Karnataka 560001, India. Throughout these Terms, the terms “we,” “us,” and “our” refer to The Bear House. We offer this Website, including all information, tools, and services available on the Site, to you (the “User”) on the condition that you accept all terms, conditions, policies, and notices contained herein. This electronic record is generated by a computer system and does not require any physical or digital signature.
              <br />
              <br />
              By visiting our Site and/or purchasing products or services from us, you engage in our “Service” and agree to be bound by these Terms of Service (“Terms”), including any additional terms, conditions, and policies referenced herein or available via hyperlink. If you do not agree to all of these Terms, you may not access or use the Website. We reserve the right to update, change, or replace any part of these Terms at any time by posting the updates on our Website. Your continued use of the Site following any changes constitutes acceptance of those changes
              </p>
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
}
